name: ribbonc
version: 0.1.0.0

language: GHC2021

default-extensions:
    - LambdaCase
    - BlockArguments
    - MultiWayIf

    - UndecidableInstances
    - DefaultSignatures

    - PatternSynonyms
    - ViewPatterns
    - RecordWildCards
    - NamedFieldPuns

    - OverloadedRecordDot
    - DuplicateRecordFields
    - NoFieldSelectors
    - DisambiguateRecordFields

    - OverloadedStrings

ghc-options:
    - -Wall

dependencies:
    - base
    - containers
    - bimap
    - mtl
    - hashable
    - array
    - text
    - bytestring
    - pretty
    - directory
    - filepath
    - parallel-io
    - optparse-applicative

build-tools:
    - alex

executables:
    ribbonc:
        main: Main.hs
        source-dirs: src
