name: ribbonc
version: 0.1.0.0

default-extensions:
    - LambdaCase
    - BlockArguments
    - MultiWayIf

    - ScopedTypeVariables
    - TypeApplications
    - AllowAmbiguousTypes

    - ImportQualifiedPost

    - FlexibleInstances
    - FlexibleContexts
    - UndecidableInstances
    - MultiParamTypeClasses
    - FunctionalDependencies
    - DefaultSignatures

    - PatternSynonyms
    - ViewPatterns

    - TupleSections

    - RecordWildCards

    - GeneralizedNewtypeDeriving
    - DerivingStrategies
    - DeriveFunctor
    - DeriveFoldable
    - DeriveTraversable


ghc-options:
    - -Wall

dependencies:
    - base
    - containers
    - bimap
    - mtl
    - hashable
    - array
    - text
    - bytestring
    - pretty

build-tools:
    - alex

executables:
    ribbonc:
        main: Main.hs
        source-dirs: src
